name: Lint Code Base

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write   # needed so the bot can push fixes

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or match your project version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (with autofix)
        run: npm run lint -- --fix

      - name: Commit & push fixes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: apply linter autofixes"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          add_options: "-A"
